### ISSUE TITLE
Change formatting removal from PM to comment on post

### ISSUE THREAD

**Issue by himekat** [sofaworks/nosleepautobot#10]
When the bot removes a post for formatting issues, instead of sending a PM about it (from the subreddit), please have the bot comment on the story directly. In addition to the current stuff the message says, please have a link at the bottom that says: 

> **Once you have fixed your formatting issues, please [[click here]] to request re-approval.** The re-approval process is manual, so send a single request only. Multiple requests do not mean faster approval; in fact they will clog the modqueue and result in re-approvals taking even more time.

The "click here" part should either send a PM to the subreddit with the below message/information, or open a message window pre-populated with the below information so that the user can manually send it:

> [[MY POST]] to /r/NoSleep was flagged for formatting issues. I have fixed those issues and am now requesting re-approval. 

> *Note to moderation team:* if this story is eligible for re-approval, remember to remove the bot's comment from it.

**Comment by birryree** [comment]
This was closed by fcad9cfa4c9198166337a39ea702803a10d6cb01
