### ISSUE TITLE
Invalid word allowed in NoSleep post title

### ISSUE THREAD

**Issue by himekat** [sofaworks/nosleepautobot#101]
This post allowed the word "expanded" to be listed in the parentheses of a title, which should not be allowed:

https://www.reddit.com/r/nosleep/comments/vysa15/when_the_world_fell_away_expanded/

See https://github.com/sofaworks/nosleepautobot/blob/master/bot.py#L202

**Comment by leikahing** [comment]
The bot never saw this post because it wasn't being found during a broken hour-long search window where no results were being returned. Closing~
