### ISSUE TITLE
NoSleepAutoBot posted in another subreddit

### ISSUE THREAD

**Issue by himekat** [sofaworks/nosleepautobot#102]
NoSleepAutoBot posted a comment in the /r/Politiek subreddit here:

https://www.reddit.com/r/Politiek/comments/sxuwru/comment/ifrvjyc/

Interestingly, the post is five months old, but it did this three days ago...

**Comment by leikahing** [comment]
This looks like a weird blip in Reddit search that happened during a bot run.

From the log...

```
1483261421580197891 2022-07-11 21:18:22 2022-07-11 21:18:23 416416913   nosleep-autobot 3.229.20.9  Local7  Info    app/worker.1    
INFO:root:Processing submissions: [Submission(id='45yobv'), Submission(id='52fey3'), Submission(id='l7oifs'), Submission(id='sxuwru')]
```

And given that the query to search for this is...

https://github.com/sofaworks/nosleepautobot/blob/8bac6e1ce801ea2dd1b8ce22711709579e98d26b/bot.py#L399

I think this might be a blip in Reddit during that 2 minute window.

I'll put in some safeguards so it won't do this kind of posting.
