### ISSUE TITLE
Rule-breaking title issue

### ISSUE THREAD

**Issue by himekat** [sofaworks/nosleepautobot#125]
The following story has a rule-breaking title: https://www.reddit.com/r/nosleep/comments/zzenot/the_vulture_house_part_1_of_2/

(Part 1 of 2) shouldn't be allowed as a title, yet it appears here in "The Vulture House (Part 1 of 2)".

Only a single part should be allowed (e.g., Part 1 or Part One).

**Comment by leikahing** [comment]
This wasn't an actual bug, the bot was just not running due to issues connecting to the database.
