### ISSUE TITLE
Two spaces at the end of a line followed by a single return should be considered valid formatting for a post

### ISSUE THREAD

**Issue by himekat** [sofaworks/nosleepautobot#13]
We recently ran into a story on /r/NoSleep that utilized the following format:

> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc consequat consequat elit. Donec ut dignissim tellus.  
Integer vehicula, sem ut condimentum porta, lacus mauris venenatis elit, eget cursus lectus ante sed leo. Mauris at leo porta, semper diam eget, viverra nulla. Praesent sit amet felis nisl. Etiam quis luctus diam. Ut tempor, quam a pellentesque dictum, mauris metus blandit nibh, et aliquam enim quam at ipsum. Pellentesque nec tellus suscipit nisi gravida fringilla id at augue. Nam auctor neque sed luctus aliquam.  
Donec quis arcu at ex consequat accumsan. Proin eu fermentum tortor. Ut malesuada lorem sed tortor sagittis, eu pharetra augue egestas. Nunc aliquam fermentum porta.  
Aliquam volutpat erat nec turpis cursus rhoncus. Quisque tempor sapien a ipsum hendrerit, non tristique velit bibendum. Cras mattis luctus nulla, sed ultrices velit. Praesent a magna nec tellus condimentum aliquam.  
Nulla nibh turpis, pharetra quis semper sed, posuere vel quam. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Duis ultricies est in metus tincidunt euismod.   

This format is: lines or paragraphs which have two spaces at the end of them, followed by a single return. Since the bot doesn't recognize this as a valid paragraph break style, if the story is more than 350 words, the bot will reject it for formatting issues.

Although this formatting isn't a common case and doesn't conform to the "double-return to create new paragraphs" format, the mods have deemed it acceptable. The bot should not reject stories formatted like this for formatting issues.

**Comment by birryree** [comment]
This issue was fixed by 98f862a.
