### ISSUE TITLE
Bot is flaky on enforcing 24-hour posting rule

### ISSUE THREAD

**Issue by himekat** [sofaworks/nosleepautobot#20]
User [/u/CigarettesAndSongs](https://www.reddit.com/user/CigarettesAndSongs) triggered a bug/mishap with the bot wherein they posted the same story (same title and text) twice in a 45 minute period and the bot *did not* remove the second, duplicate posting. 

The stories were:

* https://www.reddit.com/r/nosleep/comments/5wgjkv/little_shop_of_horace/
* https://www.reddit.com/r/nosleep/comments/5wgpfh/little_shop_of_horace/

The bot should *always* remove stories if the user has an active story (non-removed) on /r/NoSleep within the last 24-hours.

**Comment by leikahing** [comment]
I'm closing this due to no repro.
