### ISSUE TITLE
Make the bot remove "unreadable" wall-of-text posts

### ISSUE THREAD

**Issue by himekat** [sofaworks/nosleepautobot#6]
One of /r/NoSeep's rules is that all story posts must be formatted in a readable fashion. One of the biggest issues we have is people posting "walls of text" -- entire stories without paragraph breaks, like [this](http://i.imgur.com/x6vNgmv.jpg) (and worse -- that's actually a really mild example).

We'd like to have Noxbot automatically remove posts that have any paragraphs of text with more than 350 words in them. 

When a post is removed, a PM should be send (from the subreddit) to the user with the following text:

> [[YOUR POST]] has been temporarily removed from /r/NoSleep because it appears to have formatting issues which make it unreadable. In this case, you have one or more paragraphs with more than 350 words. Please break up your story into smaller paragraphs. You can create paragraphs by pressing "Enter" twice at the end of a line.

> Once you have fixed the formatting, please respond to this PM for re-approval. The re-approval  process is manual, so send a single request only. Multiple requests do not mean faster approval; in fact they will clog the modqueue and result in re-approvals taking even more time.

Please test this change before implementation and alert /u/Himekat so she can watch the bot's behavior on /r/NoSleep.

PS. If it would make it easier to do this by character count instead of word count, I can provide a character count that would be appropriate.

**Comment by birryree** [comment]
Both this issue and #7 are fixed by 1a0cb90 / a931c47. The commits also introduce a new message formatting system to alert people to multiple issues affecting their comments.
