### ISSUE TITLE
Make bot remove "unreadable" code block posts

### ISSUE THREAD

**Issue by himekat** [sofaworks/nosleepautobot#7]
A common formatting issue we see in /r/NoSleep is for people to have a tab or series of spaces at the beginning of their paragraphs (like you might in a traditional word processor or book). Unfortunately, reddit renders *four spaces* at the beginning of a line as a block of code, which almost 100% of the time makes the story unreadable. 

Please have the bot check the beginning of every paragraph/line in a story. If any paragraph/line starts with four or more spaces, the story should be removed (as it is more than likely unreadable). 

When a post is removed, a PM should be send (from the subreddit) to the user with the following text:

> [[YOUR POST]] has been temporarily removed from /r/NoSleep because it appears to have formatting issues which make it unreadable. In this case, you have one or more paragraphs or lines which begin with four or more spaces. 

> On reddit, lines beginning with four or more spaces are treated as blocks of code and make your story unreadable. Please remove spaces at the beginning of paragraphs/lines. You can create paragraphs by pressing "Enter" twice at the end of a line if you haven't already done so.

> Once you have fixed the formatting, please respond to this PM for re-approval. The re-approval process is manual, so send a single request only. Multiple requests do not mean faster approval; in fact they will clog the modqueue and result in re-approvals taking even more time.

Please test this change before implementation and alert /u/Himekat so she can watch the bot's behavior on /r/NoSleep.

**Comment by birryree** [comment]
Both this issue and #6 are fixed by 1a0cb90 / a931c47. The commits also introduce a new message formatting system to alert people to multiple issues affecting their comments.
