### ISSUE TITLE
Bot is not posting series reminder comment if post is tagged "NSFW"

### ISSUE THREAD

**Issue by himekat** [sofaworks/nosleepautobot#73]
It looks like the bot isn't posting the "series reminder" comment on series posts if they've been marked "NSFW" through reddit's interface, even if they are properly flaired as "Series" or have allowable series tags in their title. 

Examples:

https://www.reddit.com/r/nosleep/comments/bh3jyv/living_in_an_rv_park_pt_2/
https://www.reddit.com/r/nosleep/comments/bgx5ut/hell_is_other_rabbits_father/
https://www.reddit.com/r/nosleep/comments/bgd2nb/weird_shit_ive_seen_in_the_army_fob_scorpion/

**Comment by leikahing** [comment]
Bot's account wasn't set to retrieve `nsfw` content in searches, which extends to API usage.

**Comment by leikahing** [comment]
Closing this issue as changing the bot account's settings fixes it.
