### ISSUE TITLE
Add users to approved users list in /moderation/activity_tracker.py

### ISSUE THREAD

**Issue by himekat** [sofaworks/nosleepautobot#79]
NoSleep now has moderator team leads and we’d like them to be able to use the Activity Tracker portion of the bot’s functionality. Please add the following users as approved users so that they can use bot PMs to track moderator activity:

* /u/flard
* /u/onyxoctopus
* /u/desidarling

**Comment by leikahing** [comment]
This has been updated in Heroku.
