### ISSUE TITLE
Enhancements to /moderation/activity_tracker.py

### ISSUE THREAD

**Issue by himekat** [sofaworks/nosleepautobot#80]
We need a post count-specific report that can be generated on request which includes total number of posts made to /r/nosleep, number of posts approved by any/all mods, and number of posts removed by any/all mods within a specific time period. 

**Sample Input (this is just an example and can be adjusted as makes sense):**

`posts --startdate 2019-08-19 --enddate 2019-08-21`

Note: if dates are the same, only that one day is being requested. Or you can make up a different way to only request a single day of data, I don't care. But single day requests should be allowed.

**Generates a table like:**

 Date | Total Posts to NoSleep | Approved Posts | Removed Posts
------------ | ------------- | --------------- | ---------------
2019-08-19 | 50 | 25 | 25
2019-08-20 | 70 | 40 | 30
2019-08-21 | 60 | 30 | 30

**Comment by leikahing** [comment]
This is done and uses the following format to work...

```
posts --start YYYY-MM-DD --end YYYY-MM-DD
```

**Comment by himekat** [comment]
As an additional note, using the same `--start` and `--end` date will give you data for just that one day.
