### ISSUE TITLE
Disable 24-Hour Rule For "Beyond Belief" Event

### ISSUE THREAD

**Issue by himekat** [sofaworks/nosleepautobot#91]
Flip the 24-Hour Rule flag in Heroku sometime on the evening of March 1st in preparation for "Beyond Belief" event which will run from March 2nd until March 5th. The subreddit will be closed for entries prior to that, so the exact time doesn't matter as long as it's done before 11:59PM.

**Comment by leikahing** [comment]
Disabled `AUTOBOT_ENFORCE_TIMELIMIT`
