### ISSUE TITLE
Usernames with hyphens aren't processed/handled properly

### ISSUE THREAD

**Issue by himekat** [sofaworks/nosleepautobot#99]
It appears that the reddit search functionality isn't handling users with hyphens in their usernames properly. 

Example:

This user posted three stories over the course of two 24-hour periods, which should have been removed by the bot but weren't.

https://www.reddit.com/user/then-system-1022

Family Mystery (tglfmw) @ 5:56pm Mar 17
Lucky Rabbit Foot (tg01n8) @ 10:43pm Mar 16
Reverse Surgery (tfoav4) @ 2:10pm Mar 16

**Comment by leikahing** [comment]
This is fixed with #100
